### ISSUE TITLE
branding

### ISSUE THREAD

**Issue by pdurbin** [QualitativeDataRepository/dataverse-previewers#1]
These previewers are great! However, I'm playing around with them over at https://github.com/IQSS/dataverse-ansible/issues/52#issuecomment-478789201 and the first thing I noticed is that "QDR" appears prominently at the top, like this:

![Screenshot from 2019-04-01 19-52-20](https://user-images.githubusercontent.com/21006/55366720-f3f24500-54b7-11e9-83ff-268aaa14e9f3.png)

Is it possible to customize this branding?

**Comment by adam3smith** [comment]
and give up on our plans for world domination? NEVER!!! 
 
(@qqmyers will have the probably more boring, if more helpful, actual answer to this)

**Comment by pdurbin** [comment]
Heh. Oh, wait, like the README says (who reads documentation?) if you put an image here:

`/usr/local/glassfish4/glassfish/domains/domain1/docroot/logos/preview_logo.png`

It shows up instead of the QDR logo:

![Screenshot from 2019-04-01 21-51-27](https://user-images.githubusercontent.com/21006/55370430-7256e300-54c8-11e9-9445-63c7b8bec6d1.png)

As someone who doesn't always read the documentation, I skipped over this step and I imagine others might too. Should there be no logo out of the box? And keep the instructions on how to add one?

**Comment by qqmyers** [comment]
That's definitely the world domination question - we'll stop with just the people who don't read documentation...

The problem with no logo is that things then appear broken unless you read - perhaps we can make a logo that fills the space and notes that you can customize by reading the docs... or ...?

**Comment by pdurbin** [comment]
Maybe out of the box there could be a blank/white image that fills the space as a placeholder. I wouldn't suggest putting any text on it because many installations of Dataverse might be happy to use the instance of the tools you've already put on github.io. Harvard Dataverse, for example, uses the github.io version of Data Explorer. It's one less thing to host and maintain.

**Comment by qqmyers** [comment]
FWIW - you can still use the github hosted version with a custom logo...

**Comment by pdurbin** [comment]
@qqmyers sure, but are you open to a pull request where a transparent image the same size as QDR_Logo_Dataverse.png is added (transparent_logo.png or whatever) and then the following line is changed to load transparent_logo.png instead of QDR_Logo_Dataverse.png?

https://github.com/QualitativeDataRepository/dataverse-previewers/blob/86fc269d23eb19d520450c6a63f5402d6a7268d0/previewers/js/retriever.js#L113

The README would need to be tweaked slightly as well. This line: "If you do not supply a logo, a generic QDR logo will be used."

I'm cool with world domination by QDR but maybe your logo could appear that the bottom of the page instead? Credit where credit's due for creating these external tools!

**Comment by adam3smith** [comment]
From my end, I'd be fine with the transparent logo as default. Jim, does that sound OK with you?

I actually don't think we'll want the QDR logo to appear in the footer -- since QDR is a specific repository (other than Dataverse, which is both a software project _and_ a repository) that'd be confusing. A single credit line in the footer would be nice, though.

**Comment by pdurbin** [comment]
One nice way to promote QDR in the footer might be to include a link to this git repo.

I added "Feedback is welcome via [repo]" to the bottom of the Dataverse metrics page:

![Screen Shot 2019-04-02 at 8 57 32 AM](https://user-images.githubusercontent.com/21006/55404252-79f8a500-5525-11e9-8aba-6dcdd81c4bd1.png)

Lots of people will look at a URL like qualitativedatarepository.github.io and know that it corresponds to https://github.com/qualitativedatarepository so the URL itself is good advertising for QDR when installations don't choose to self-host.

**Comment by qqmyers** [comment]
@pdurbin, @adam3smith - how's this (updated in github) - a blank white logo and small tagline at the bottom. Feel free to suggest or PR for further changes...

**Comment by pdurbin** [comment]
@qqmyers I just re-tested as of 02db594 and it looks great:

![Screen Shot 2019-04-02 at 1 16 55 PM](https://user-images.githubusercontent.com/21006/55422463-b5a56600-5549-11e9-8a62-4800bead9ab2.png)

(I also tested a custom logo and it still works.)

Thanks! Closing. For the "File uploaded on undefined" in the screenshots above I opened a new issue: #4
