### ISSUE TITLE
TSV Previewer

### ISSUE THREAD

**Issue by pdurbin** [QualitativeDataRepository/dataverse-previewers#11]
I just tried out the new CSV previewer and it's awesome. I left some screenshots in https://github.com/IQSS/dataverse/issues/6256

To get it to work with TSV files (and files like Stata, etc that went through the ingest process), I made a tiny tweak to what's in the README, changing

"contentType":"text/comma-separated-values" 

to

"contentType":"text/tab-separated-values"

I think this would be a nice addition to the README. I'm happy to make a pull request if you'd like or you could tag this issue with "hacktoberfest" and reply on the thread at https://groups.google.com/d/msg/dataverse-community/ootwCQL-4K4/00QO3__8CQAJ that @poikilotherm started. 😄

**Comment by qqmyers** [comment]
@pdurbin Go for it. No need to tag it, it will still count towards your t-shirt.

**Comment by discombobulateme** [comment]
@pdurbin how can I help here?

**Comment by pdurbin** [comment]
@discombobulateme hi! I believe the "diff" of the pull request that you would make should look something like this:

```
[pdurbin@tabby dataverse-previewers]$ git diff
diff --git a/README.md b/README.md
index 011d6ef..fd3015c 100644
--- a/README.md
+++ b/README.md
@@ -278,6 +278,25 @@ You should be able to cut/paste any/all of the commands below to run on your Dat
 >  \\"contentType\\":\\"text/comma-separated-values\\"
 >}"
 
+>curl -X POST -H 'Content-type: application/json' http://localhost:8080/api/admin/externalTools -d \\
+>"{
+>  \\"displayName\\":\\"View Data\\",
+>  \\"description\\":\\"View the spreadsheet data.\\",
+>  \\"scope\\":\\"file\\",
+>  \\"type\\":\\"explore\\",
+>  \\"toolUrl\\":\\"https://qualitativedatarepository.github.io/dataverse-previewers/previewers/CSVPreview.html\",
+>  \\"toolParameters\\": {
+>      \\"queryParameters\\":[
+>        {\\"fileid\\":\\"{fileId}\\"},
+>        {\\"siteUrl\\":\\"{siteUrl}\\"},
+>        {\\"key\\":\\"{apiToken}\\"},
+>        {\\"datasetid\\":\\"{datasetId}\\"},
+>        {\\"datasetversion\\":\\"{datasetVersion}\\"}
+>      ]
+>    },
+>  \\"contentType\\":\\"text/tab-separated-values\\"
+>}"
+
 >curl -X POST -H 'Content-type: application/json' http://localhost:8080/api/admin/externalTools -d \\
 >"{
 >  \\"displayName\\":\\"View Annotations\\",
[pdurbin@tabby dataverse-previewers]$ 
```

The idea is to edit README.md to duplicate the installation instructions for the "View the spreadsheet data" tool and change "contentType" in the duplicate from "comma" to "tab". This way the tool will be available for both file types (CVS and TSV).

With these instructions in place, installations of Dataverse will be able to preview spreadsheets like in the screenshots below.

![66243138-74953680-e6d1-11e9-88d6-bee647f11a19](https://user-images.githubusercontent.com/21006/66254881-ad252680-e74a-11e9-8cfc-3d3337f6f08f.png)

![66243140-74953680-e6d1-11e9-81e7-30f1ba4da25d](https://user-images.githubusercontent.com/21006/66254880-ad252680-e74a-11e9-9477-ac7aa90e9e2f.png)

If you'd like to play with the example above, please try clicking "Explore" at https://dev2.dataverse.org/dataset.xhtml?persistentId=doi:10.5072/FK2/VKI4P5

**Comment by pdurbin** [comment]
@qqmyers when you get a chance, can you please add a "hacktoberfest" label to this issue?

**Comment by qqmyers** [comment]
@pdurbin - OK, but it isn't needed when people already know about the issue - it counts whether it is labeled or not.

**Comment by discombobulateme** [comment]
@pdurbin should I fork or commit directly?

**Comment by pdurbin** [comment]
@qqmyers ok, sorry, I'm not very familiar with Hacktoberfest apart from what @poikilotherm posted at https://groups.google.com/d/msg/dataverse-community/ootwCQL-4K4/00QO3__8CQAJ 😄 

@discombobulateme please fork the repo and make a pull request from there. Thanks!

**Comment by discombobulateme** [comment]
Dear @pdurbin I think I made it :O OMGGGGGGGG (I'm VERY excited!!). 
By the way, what a beautiful well made documentation there's in Dataverse. 
Please let me know if it's correct :)
And thank you soooo much for your help

**Comment by pdurbin** [comment]
@discombobulateme you're welcome! I just left you a review in pull request #12. Thanks for creating it! 🎉 🎉 🎉 

Also, I'm glad you like the Dataverse documentation. 😄 

I'd also like to mention that you can help translate Dataverse if you want: http://guides.dataverse.org/en/4.17/installation/config.html#how-to-help-translate-dataverse-into-your-language 😄

**Comment by pdurbin** [comment]
@discombobulateme thanks again for making pull request #12 and thank you to @qqmyers for merging it! Our first Hactoberfest pull request has been merged! I'll share the good news on the " It's Hacktoberfest!" thread at https://groups.google.com/d/msg/dataverse-community/ootwCQL-4K4/00QO3__8CQAJ

@discombobulateme if you'd like to make any more contributions, I'm happy to help you find something to work on! During work hours a good place to find me is http://chat.dataverse.org . You can find other ways to contact us at https://dataverse.org/contact

Thanks again! 🎉 🎉 🎉
