### ISSUE TITLE
CSV/TSV Viewer is labelled 'Csv Viewer'

### ISSUE THREAD

**Issue by qqmyers** [QualitativeDataRepository/dataverse-previewers#13]
If we're going to use the tabular viewer for both csv and tsv files, should the label shown on the preview page reflect that, or be generic like 'Table Preview' or 'Spreadsheet Viewer'? Looks like  a simple update in the html file.

**Comment by adam3smith** [comment]
I like "Spreadsheet Viewer"

**Comment by qqmyers** [comment]
@anncie-pcss - do you want to make this change? Could also change the csv.js filename too, but users don't see that. If not, let me know if "Spreadsheet Viewer" is OK as a label and I can update.

**Comment by annacieplicka** [comment]
done :)
