### ISSUE TITLE
Curl command  yields status:"error", message:"Endpoint available from localhost only.

### ISSUE THREAD

**Issue by mshariful** [QualitativeDataRepository/dataverse-previewers#22]
Hello,
I tried to execute this curl command 

sudo curl -X POST -H 'Content-type: application/json' http://localhost:8085/api/admin/externalTools -d \ "{ \"displayName\":\"View Image\", \"description\":\"Preview an image file.\", \"scope\":\"file\", \"type\":\"explore\", \"toolUrl\":\"https://qualitativedatarepository.github.io/dataverse-previewers/previewers/ImagePreview.html\", \"toolParameters\": { \"queryParameters\":[ {\"fileid\":\"{fileId}\"}, {\"siteUrl\":\"{siteUrl}\"}, {\"key\":\"{apiToken}\"}, {\"datasetid\":\"{datasetId}\"}, {\"datasetversion\":\"{datasetVersion}\"} ] }, \"contentType\":\"image/png\" }"

but I get this message:
{ status:"error", message:"Endpoint available from localhost only. Please contact the dataverse administrator"}

I have installed Dataverse using "DataverseEU Docker module". It is running on a linux (Ubuntu)
at http://localhost:8085/dataverse/root

Could you please suggest how to fix it?

Thank you very much.

Regards,
Sharif

**Comment by pdurbin** [comment]
@mshariful weird. Can you "ssh" into the Docker container and try the same command on port 8080? (I would try listing the tools first.) That should be the port on which Dataverse is running. If you want, you can join us in http://chat.dataverse.org and we can try to help.

**Comment by pdurbin** [comment]
@mshariful thanks for talking this out in IRC today. I'm glad you're all set. When you have a moment, can you please open an issue at https://github.com/IQSS/dataverse-docker about this and then close this issue? (And link to the new issue here, please.) Thanks!

**Comment by qqmyers** [comment]
as notes, this is a Dataverse rather than previewer issue, so closing the entry here.

**Comment by pdurbin** [comment]
@qqmyers thanks. I just checked dataverse-docker and I don't see an issue so heads up to @4tikhonov about this.

**Comment by pdurbin** [comment]
@mshariful thanks for creating https://github.com/IQSS/dataverse-docker/issues/29 🎉
