### ISSUE TITLE
Issues turning on Previewers in dataverse.harvard.edu

### ISSUE THREAD

**Issue by djbrooke** [QualitativeDataRepository/dataverse-previewers#28]
We tried to turn on previewers in dataverse.harvard.edu and were mostly not successful. We've taken them down for now. 

- This .tab file previewed successfully: https://dataverse.harvard.edu/file.xhtml?persistentId=doi:10.7910/DVN/UEOK3H/RAVQSR
- This .pdf file did not preview successfully: https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/QUH8KT. It just spins and shows nothing in both in the preview window and in the external tool view.
- This .txt file does not preview successfully: https://dataverse.harvard.edu/file.xhtml?persistentId=doi:10.7910/DVN/GKJWUG/4WWEOC. It shows the error "Unable to retrieve file. If problem persists (has your login timed out?), report error code: error to the repository administrator."

I discussed this with @kcondon and @scolapasta and the suspicion is that it has to do with redirects (I'll ask @scolapasta to fill in the details here). 

More details in https://github.com/IQSS/dataverse.harvard.edu/issues/42

**Comment by scolapasta** [comment]
On S3, dataverse will redirect calls to an S3 link when you try to download the file.

By default the API for download (at least with curl) does not by follow the redirect. You have to add -L to the call. (we're currently unsure of why the tab* works, but it is the anomaly).

* due to ingest, it must do something differently

So basically, we think these previewers (and other external tools) should make sure to follow redirects.

**Comment by qqmyers** [comment]
If you're redirecting to S3 for downloads, you may be seeing a CORS issue unless you support that on S3.

**Comment by scolapasta** [comment]
Are you saying that the previewers already support redirects when calling the API? If so, sure we can also look re: cors on the s3 side.

**Comment by qqmyers** [comment]
I think they do because the browser does automatically. A CORS issue should be visible in the browser debug console, so you can tell before digging too far.

If you get details of what's needed at Amazon to enable CORS, let me know and I'll add it to the docs.

**Comment by scolapasta** [comment]
Aha, yes it is CORS:
![image](https://user-images.githubusercontent.com/4268292/70742148-ddf57f00-1cea-11ea-898b-ca45fb0d14c4.png)

**Comment by djbrooke** [comment]
Thanks @qqmyers @scolapasta @kcondon - I've requested the Harvard LTS team to allow CORS for dataverse.harvard.edu. I'll close this and update the docs if this ends up being the solution.

**Comment by djbrooke** [comment]
LTS updated the CORS settings on Harvard Dataverse and we've since enabled the previewers. Will make a PR to the docs here when I have time.
