### ISSUE TITLE
File uploaded on undefined

### ISSUE THREAD

**Issue by pdurbin** [QualitativeDataRepository/dataverse-previewers#4]
I'm getting "File uploaded on undefined" and I'm not sure why. Here's a screenshot:

![Screen Shot 2019-04-02 at 1 16 55 PM](https://user-images.githubusercontent.com/21006/55422506-c8b83600-5549-11e9-89cb-98575cd4da83.png)

**Comment by qqmyers** [comment]
@pdurbin - hmm, the 'root' cause is because there is no creationDate listed for the file in the response to http://phoenix.dataverse.org/api/datasets/167/versions/1.0 - I'm not sure why that should be though.

**Comment by qqmyers** [comment]
@pdurbin - if you're seeing this all the time, perhaps I added creationDate to the metadata and that isn't in a PR yet, but I don't see that it should be inconsistent between datasets/files on one instance...

**Comment by qqmyers** [comment]
That's it - I added a line in JSONPrinter 4 months ago but I don't think it made it to a PR - I'll create an issue/PR for it.

**Comment by qqmyers** [comment]
Addressed with https://github.com/IQSS/dataverse/pull/5714...

**Comment by pdurbin** [comment]
> also added an if statement to not show the date if it isn't sent

I just tested 6309951 and this fix works fine. Closing. Thanks!

Heads up that Dataverse 4.12 is already out so maybe your fix will be in 4.13? Stay tuned. :smile:
